export interface EventoI {
    
    id_evento: number,
    id_actividad: number, 
    id_estudiante: number,
    data_start: string,
    hour_start: string,
    data_end: string,
    hour_end: string,
    check_download: number,
    check_inicio: number,
    check_fin: number,
    check_answer: number,
    count_video: number,
    check_video: number,
    check_documento: number,
    check_a1: number,
    check_a2: number,
    check_a3: number,
    check_profile: number,
    check_Ea1: number,
    check_Ea2: number,
    check_Ea3: number,
    oculto: number
}